### ISSUE TITLE
Any Apk for 3.0 to test it?

### ISSUE THREAD

**Issue by KR4U7H3R** [Coolboyrajat/Fluid-Navigation-Gesture#1]
Hey, do you need someone to test your app? I am currently using the old one, and would like to beta test if needed.

Regards

**Comment by Coolboyrajat** [comment]
It's a prototype model but still their are some interactions to go through the layout, Do check it out if you are interested by clicking this [link](https://www.figma.com/proto/mBgc3PmCIkM0hG3isAGR6p/Fluid-Navigation-Gesture?node-id=4%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=4%3A2) ,,, just download figma app sign in with any random acc. and go with the preview.

● If there is any else you can want to say, you can show up in [Discord](https://discord.gg/YqeTbs3Y), I'm happy to discuss.
● You can also check it [Telegram++](https://github.com/Coolboyrajat/Telegram-Plus) design repository.
